-- create a db 
CREATE DATABASE IF NOT EXISTS kpi;

-- create admin
CREATE USER IF NOT EXISTS 'admin'@'localhost' IDENTIFIED BY 'admin_pwd';
-- GRANT ALL PRIVILEGES ON *.* TO 'admin'@'localhost';
-- GRANT SELECT ON `performance_schema`.* TO 'admin'@'localhost';
-- FLUSH PRIVILEGES;

-- create tables
CREATE TABLE IF NOT EXISTS kpi.flights (id INT UNIQUE AUTO_INCREMENT NOT NULL PRIMARY KEY, flight_id VARCHAR(256) NOT NULL, origin VARCHAR(256) NOT NULL, destination VARCHAR(256) NOT NULL, arrived_at DATETIME NOT NULL);

CREATE TABLE IF NOT EXISTS kpi.distances (id INT UNIQUE AUTO_INCREMENT NOT NULL PRIMARY KEY, id_flight INT NOT NULL UNIQUE, direct FLOAT, flown FLOAT, kea FLOAT, FOREIGN KEY (id_flight) REFERENCES kpi.flights(id));

-- CREATE TABLE IF NOT EXISTS kpi.routes (id INT UNIQUE AUTO_INCREMENT NOT NULL PRIMARY KEY, id_flight INT NOT NULL, route VARCHAR(256) NOT NULL, FOREIGN KEY (id_flight) REFERENCES flights(id));

CREATE TABLE IF NOT EXISTS kpi.fixpoints (id INT UNIQUE AUTO_INCREMENT NOT NULL PRIMARY KEY, name VARCHAR(256) NOT NULL, lat INT NOT NULL, lon INT NOT NULL);

CREATE TABLE IF NOT EXISTS kpi.decimalfixpoints (id INT UNIQUE AUTO_INCREMENT NOT NULL PRIMARY KEY, name VARCHAR(256) NOT NULL, lat INT NOT NULL, lon INT NOT NULL);

